version: '3.8'
services:

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    network_mode: host
    expose:
      - 80
    volumes:
      - .:/etc/nginx/
    environment:
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=www.wjmcat.cn,bayi.wjmcat.cn,blog.wjmcat.cn,python-wechaty.wjmcat.cn
      - LETSENCRYPT_HOST=www.pre-angel.com,pre-angel.com
